config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :presentations,:member => { :download => :get, :new_version=>:post, :preview_publish=>:get,:publish=>:post,:request_resource=>:post, :update_annotations_ajax=>:post }
  map.resources :subscriptions
  map.resources :specimens
  map.resources :samples

  map.resources :events

  map.resources :strains, :collection=>{:existing_strains=>:get, :existing_strains_for_create=>:get, :show_existing_strain=>:get, :new_strain_form => :get}

  map.resources :publications,:collection=>{:fetch_preview=>:post},:member=>{:disassociate_authors=>:post,:update_annotations_ajax=>:post}

  map.resources :experiment_types, :collection=>{:manage=>:get}

  map.resources :organisms, :member=>{:visualise=>:get}

  map.resources :technology_types, :collection=>{:manage=>:get}

  map.resources :measured_items

  map.resources :investigations

  map.resources :studies

  map.resources :experiments,:member=>{:update_annotations_ajax=>:post}

  map.resources :saved_searches

  map.resources :biosamples, :collection=>{:existing_strains=>:get, :existing_specimens=>:get, :existing_samples=>:get, :strain_form => :get, :create_strain => :post, :update_strain => :put,  :create_specimen_sample => :post, :strains_of_selected_organism => :get}

  map.resources :data_files, :collection=>{:test_asset_url=>:post},:member => {:download => :get,:plot=>:get, :data => :get,:preview_publish=>:get,:publish=>:post, :request_resource=>:post, :update_annotations_ajax=>:post, :explore=>:get},:new=>{:upload_for_tool => :post}  do |data_file|
    data_file.resources :studied_factors, :collection =>{:create_from_existing=>:post}
  end
  
  map.resources :spreadsheet_annotations, :only => [:create, :destroy, :update]
  
  map.resources :uuids

  map.resources :institutions,
    :collection => { :request_all => :get } do |institution|
    institution.resources :avatars, :member => { :select => :post }, :collection => { :new => :post }
  end

  map.resources :models, 
    :member => { :download => :get, :execute=>:post, :request_resource=>:post,:preview_publish=>:get,:publish=>:post, :builder=>:get, :submit_to_jws=>:post, :simulate=>:post, :update_annotations_ajax=>:post },
    :collection=>{:build=>:get}

  map.resources :people, :collection=>{:select=>:get,:get_work_group =>:get}, :member=>{:admin=>:get}  do |person|
    person.resources :avatars, :member => { :select => :post }, :collection => { :new => :post }
  end

  map.resources :projects,
    :collection => { :request_institutions => :get },:member=>{:admin=>:get} do |project|
    project.resources :avatars, :member => { :select => :post }, :collection => { :new => :post }
  end

  map.resources :protocols, :member => { :download => :get, :new_version=>:post, :preview_publish=>:get,:publish=>:post,:request_resource=>:post, :update_annotations_ajax=>:post } do |protocol|
    protocol.resources :experimental_conditions, :collection =>{:create_from_existing=>:post}
  end

  map.resources :users, :collection=>{:impersonate => :post, :activation_required=>:get,:forgot_password=>[:get,:post],:reset_password=>:get},
                        :member => {:set_openid => :put}

  map.resource :session, :collection=>{:auto_openid=>:get,:show=>:get,:index=>:get},:member=>{:show=>:get}

  map.resource :favourites, :member=>{:delete=>:delete},:collection=>{:add=>:post}
  
  map.resources :help_documents, :as => :help do |h|
    h.resources :help_attachments, :as => :attachments, :member => {:download => :get}, :only => [:create, :destroy]
    h.resources :help_images, :as => :images, :only => [:create, :destroy]
  end
  
  map.resources :forum_attachments, :member => {:download => :get}, :only => [:create, :destroy]

  map.resources :compounds
  
  map.search '/search/',:controller=>'search',:action=>'index'
  map.save_search '/search/save',:controller=>'search',:action=>'save'
  map.delete_search '/search/delete',:controller=>'search',:action=>'delete'

  map.svg 'svg/:id.:format',:controller=>'svg',:action=>'show'

  map.all_tags '/tags',:controller=>'tags',:action=>'index'
  map.show_tag '/tags/:id',:controller=>'tags',:action=>'show'

  map.all_anns '/tags',:controller=>'tags',:action=>'index'
  map.show_ann '/tags/:id',:controller=>'tags',:action=>'show'

  map.jerm '/jerm/',:controller=>'jerm',:action=>'index'
  
  map.country '/countries/:country_name', :controller => 'countries', :action => 'show'

  map.admin '/admin/', :controller=>'admin',:action=>'show'

  map.data_fuse '/data_fuse/',:controller=>'data_fuse',:action=>'show'

  map.feedback '/home/feedback',:controller=>'home',:action=>'feedback',:method=>:get
  map.send_feedback '/home/send_feedback',:controller=>'home',:action=>'send_feedback',:method=>:post

  map.seek_intro_demo 'home/seek_intro_demo',:controller=>'home',:action=>'seek_intro_demo',:method=>:get

  map.new_favourite_group '/favourite_groups/new', :controller => 'favourite_groups', :action => 'new', :conditions => { :method => :post }
  map.create_favourite_group '/favourite_groups/create', :controller => 'favourite_groups', :action => 'create', :conditions => { :method => :post }
  map.edit_favourite_group '/favourite_groups/edit', :controller => 'favourite_groups', :action => 'edit', :conditions => { :method => :post }
  map.update_favourite_group '/favourite_groups/update', :controller => 'favourite_groups', :action => 'update', :conditions => { :method => :post }
  map.delete_favourite_group '/favourite_groups/:id', :controller => 'favourite_groups', :action => 'destroy', :conditions => { :method => :delete }

  map.new_investigation_redbox 'studies/new_investigation_redbox',:controller=>"studies",:action=>'new_investigation_redbox',:conditions=> {:method=>:post}
  map.create_investigation 'experiments/create_investigation',:controller=>"studies",:action=>'create_investigation',:conditions=> {:method=>:post}
  
  
  map.review_work_group '/work_groups/review/:type/:id/:access_type', :controller => 'work_groups', :action => 'review_popup', :conditions => { :method => :post }  
  
  map.new_object_based_on_existing_one ':controller_name/new_object_based_on_existing_one/:id',:controller=>'#{controller_name}',:action=>'new_object_based_on_existing_one', :conditions => { :method => :post }

  

  

  map.tool_list_autocomplete '/tool_list_autocomplete', :controller=>'people', :action=>'auto_complete_for_tools_name'
  map.expertise_list_autocomplete '/expertise_list_autocomplete', :controller=>'people', :action=>'auto_complete_for_expertise_name'
  map.organism_list_autocomplete '/organism_list_autocomplete',:controller=>'projects',:action=>'auto_complete_for_organism_name'

  map.root :controller=>"home"
  map.match "index.html",:controller=>"home"
  map.match "index",:controller=>"home"

  map.signup  '/signup', :controller => 'users',   :action => 'new' 
  map.login  '/login',  :controller => 'home'
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'  
  
  map.activate '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil
  map.forgot_password '/forgot_password',:controller=>'users',:action=>'forgot_password'
  
  map.request_policy_settings '/policies/request_settings', :controller => 'policies', :action => 'send_policy_data'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/experiment_type.rb
require 'acts_as_ontology'

class ExperimentType < ActiveRecord::Base

  has_many :experiments
  
  acts_as_ontology    

  def get_child_experiments experiment_type=self
    #TODO: needs unit test
    result = experiment_type.experiments
    experiment_type.children.each do |child|
      result = result | child.experiments
      result = result | get_child_experiments(child) if child.has_children?
    end
    return result
  end
  
  def get_all_descendants experiment_type=self
    result = []
    experiment_type.children.each do |child|
      result << child
      result = result | get_all_descendants(child) if child.has_children?
    end
    return result
  end

  #FIXME: really not happy looking up by title, but will be replaced by BioPortal eventually
  def self.experimental_experiment_type_id
    at=ExperimentType.find_by_title("experiment type").id
  end

  #FIXME: really not happy looking up by title, but will be replaced by BioPortal eventually
  def self.modelling_experiment_type_id
    at=ExperimentType.find_by_title("experiment type").id
  end
 
  private




end
  

app/helpers/experiments_helper.rb
require 'acts_as_ontology_view_helper'

module ExperimentsHelper
  
  include Stu::Acts::Ontology::ActsAsOntologyViewHelper  

  #experiments that haven't already been associated with a study
  def experiments_available_for_study_association
    Experiment.find(:all,:conditions=>['study_id IS NULL'])
  end

  #only data files authorised for show, and belonging to projects matching current_user
  def data_files_for_experiment_association
    data_files=DataFile.find(:all,:include=>:asset)
    data_files=data_files.select{|df| current_user.person.member_of?(df.projects)}
    Authorization.authorize_collection("view",data_files,current_user)
  end

  def experiment_organism_list_item experiment_organism
    result = link_to h(experiment_organism.organism.title),experiment_organism.organism
    if experiment_organism.strain
       result += " : "
       result += link_to h(experiment_organism.strain.title),experiment_organism.organism,{:class => "experiment_strain_info"}
    end
    if experiment_organism.culture_growth_type
      result += " (#{experiment_organism.culture_growth_type.title})"
    end
    return result
  end



  def authorised_experiments projects=nil
    authorised_assets(Experiment, projects, "edit")
  end

  def list_experiment_samples_and_organisms attribute,experiment_samples,experiment_organisms, none_text="Not Specified"

    result= "<p class=\"list_item_attribute\"> <b>#{attribute}</b>: "

    result +="<span class='none_text'>#{none_text}</span>" if experiment_samples.blank? and experiment_organisms.blank?

    experiment_samples.each do |as|
      result += "<br/>" if as==experiment_samples.first
      organism = as.specimen.organism
      strain = as.specimen.strain
      sample = as
      culture_growth_type = as.specimen.culture_growth_type

      if organism
      result += link_to h(organism.title),organism,{:class => "experiment_organism_info"}
      end

      if strain
        result += " : "
        result += link_to h(strain.title),strain,{:class => "experiment_strain_info"}
      end

      if sample
        result += " : "
        result += link_to h(sample.title),sample
      end

      if culture_growth_type
        result += " (#{culture_growth_type.title})"
      end
      result += ",<br/>" unless as==experiment_samples.last and experiment_organisms.blank?
    end

    experiment_organisms.each do |ao|
      organism = ao.organism
      strain = ao.strain
      culture_growth_type = ao.culture_growth_type

       result += "<br/>" if experiment_samples.blank? and ao==experiment_organisms.first
      if organism
      result += link_to h(organism.title),organism,{:class => "experiment_organism_info"}
      end

      if strain
        result += " : "
        result += link_to h(strain.title),strain,{:class => "experiment_strain_info"}
      end

      if culture_growth_type
        result += " (#{culture_growth_type.title})"
      end
      result += ",<br/>" unless ao==experiment_organisms.last
    end
    result += "</p>"

    return result
  end

  def list_experiment_samples attribute,experiment_samples, none_text="Not Specified"

    result= "<p class=\"list_item_attribute\"> <b>#{attribute}</b>: "

    result +="<span class='none_text'>#{none_text}</span>" if experiment_samples.blank?

    experiment_samples.each do |as|

      organism = as.specimen.organism
      strain = as.specimen.strain
      sample = as
      culture_growth_type = as.specimen.culture_growth_type


      if organism
      result += link_to h(organism.title),organism,{:class => "experiment_organism_info"}
      end

      if strain
        result += " : "
        result += link_to h(strain.title),strain,{:class => "experiment_strain_info"}
      end

      if sample
        result += " : "
        result += link_to h(sample.title),sample       
      end

      if culture_growth_type
        result += " (#{culture_growth_type.title})"
      end
      result += ",<br/>" unless as == experiment_samples.last

    end

    result += "</p>"
    return result
  end

  def list_experiment_organisms attribute,experiment_organisms,none_text="Not specified"
    result="<p class=\"list_item_attribute\"> <b>#{attribute}</b>: "
    result +="<span class='none_text'>#{none_text}</span>" if experiment_organisms.empty?

    experiment_organisms.each do |ao|

     organism = ao.organism
     strain = ao.strain
     culture_growth_type = ao.culture_growth_type

        if organism
            result += link_to h(organism.title),organism,{:class => "experiment_organism_info"}
        end

        if strain
          result += " : "
          result += link_to h(strain.title),strain,{:class => "experiment_strain_info"}
        end
       

        if culture_growth_type
          result += " (#{culture_growth_type.title})"
        end
        result += ",<br/>" unless ao==experiment_organisms.last
      end

    result += "</p>"
    return result
  end

end

app/views/experiments/_associate_experiment.html.erb
<%
    resource_text ||= text_for_resource(resource)
    all_experiments=authorised_experiments.sort_by &:title
    all_experiments = authorised_experiments.select do |experiment|
            experiment.is_modelling?
         end if resource.is_a? Model

    project_experiments=authorised_experiments(current_user.person.projects).sort_by &:title
    project_experiments=project_experiments.select{|a| a.is_modelling?} if resource.is_a?(Model)
    select_truncate_length=120
    associated_experiments = resource.is_a?(Publication) ? resource.related_experiments : resource.experiments
%>

<div class="fold">

  <div class="foldTitle">
    <%= help_icon("Here you can associate Experiments in SEEK to this #{resource_text}. You can only associate Experiments you are authorized to edit.") -%>
    Experiments
  </div>

  <div id="associate_experiment_fold_content" class="foldContent" style="display:<%= associated_experiments.blank? ? 'none' : 'block' -%>">
    <div class="yui-u first" style="width:66%; float:left">

      <p style="color: #666666;">
        The following Experiments are involved in this <%= resource_text -%>:
      </p>
      <div id="experiment_to_list" class="box_editing_inner" style="line-height: 1.5">
        <span class="none_text" id="experiment_files">Loading...</span>
      </div>
      <div class="association_step">
        <p style="color: #666666;">
             You may select an existing Experiment or <%= link_to h("create a new Experiment here"), new_experiment_path(:create_from_asset=>:true),:popup => true%>  for the <%= resource_text -%>.
        </p>
        <% if show_relationships -%>
            <%= select_tag :possible_experiments,
              options_for_select([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}),
              {:style=>"width:90%",:onchange=>remote_function(
                :url=>{:action=>"preview",:controller=>"experiments",:element=>"experiment_preview"},
                :with=>"'id='+this.value",
                :before=>"show_ajax_loader('experiment_preview')"
              )+";check_show_add_experiment();selected_experiment();return(false);"
            } -%>
              <%= select_tag :experiment_ids,'',{:multiple=>true,:style=>"display:none;"} -%>
              <br/>
              <div id="relationship" style="display:none;">
                <%= label_tag "Relationship between the data and the model" %><br/>
                <%= select_tag :experiment_relationship_type, options_for_select([["None",0]] + RelationshipType.all.collect{|r| [r.title,r.id]}) %>
              </div>
              <br/>
        <% else %>
            <%= select_tag :possible_experiments,
                  options_for_select([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}),
                  {:style=>"width:90%",:onchange=>remote_function(
                    :url=>{:action=>"preview",:controller=>"experiments",:element=>"experiment_preview"},
                    :with=>"'id='+this.value",
                    :before=>"show_ajax_loader('experiment_preview')"
                  )+";check_show_add_experiment();return(false);"
            } -%>
            <%= select_tag :experiment_ids,'',{:multiple=>true,:style=>"display:none;"} -%>
            <br/>
            <br/>
        <% end %>
      </div>

	  <br/>
      <%= link_to_function (image("new") + " Associate with this #{resource_text}"), "addSelectedExperiment(); return(false);", :id=>"add_experiment_link", :class=>"block_link" %>

      <%= check_box_tag :include_other_project_experiments, nil, false, {:onchange=>"toggle_experiment_list();",:style=>"margin-top:0.5em;"} -%> Associate Experiments from other projects?
    </div>
  
    <%= render :partial => 'assets/preview_box', :locals => {:preview_name => 'experiment'}%>
  
  </div>
</div>
  

<script type="text/javascript">
  function selected_experiment(){
       i = $('possible_experiments').selectedIndex;
       id = $('possible_experiments').options[i].value;
       for (var j = 0; j < id_rel_array.length; j++) {
           if ((id == id_rel_array[j][0]) && (id_rel_array[j][1] == 'true'))  {
              Effect.Appear('relationship',{duration:0.2});
           }
           else if ((id == id_rel_array[j][0]) && (id_rel_array[j][1] == 'false'))  {
              $('experiment_relationship_type').selectedIndex = 0;
              Effect.Fade('relationship',{duration:0.2});
           }
       }
    }

  function toggle_experiment_list() {
          var checked = $('include_other_project_experiments').checked;
          var selection_box = $('possible_experiments');
          var option;

          selection_box.options.length = 0;

          if (checked) {
          <% ([["Select Experiment ...",0]]|all_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}).each do |df_details| -%>
              option = document.createElement("OPTION");
              option.text = '<%= escape_javascript(df_details[0]) -%>';
              option.value = '<%= df_details[1] -%>';
              try {
                  selection_box.add(option); //for older IE version
              }
              catch (ex) {
                  selection_box.add(option, null);
              }
          <% end -%>
          }
          else {
          <% ([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}).each do |df_details| -%>
              option = document.createElement("OPTION");
              option.text = '<%= escape_javascript(df_details[0]) -%>';
              option.value = '<%= df_details[1] -%>';
              try {
                  selection_box.add(option); //for older IE version
              }
              catch (ex) {
                  selection_box.add(option, null);
              }
          <% end -%>
          }
          selection_box.selectedIndex = 0;
          selection_box.onchange();
      }

<% associated_experiment_ids = resource.is_a?(Publication) ? resource.related_experiments.collect(&:id) : resource.experiments.collect(&:id) %>
  <% associated_experiment_ids.each do |associated_experiment_id|%>
    <% experiment = Experiment.find(associated_experiment_id) %>
    <% if experiment.try :can_view? -%>
      experiment_id = '<%= experiment.id -%>';
      experiment_title = '<%= experiment.title -%>';
      relationship_type = '<%= resource.is_a?(DataFile) ? escape_javascript(resource.relationship_type(experiment).try(:title) || "None") : 'None'-%>';
      addExperiment(experiment_title,experiment_id,relationship_type);
    <% end %>
<% end -%>

<% all_experiments.each do |experiment|%>
    experiment_id = '<%= experiment.id -%>';
    experiment_relationship = '<%=(experiment.is_modelling?) -%>';
    id_rel_array.push([experiment_id, experiment_relationship])
<% end -%>

<% if params[:experiment_ids] %>
  <% params[:experiment_ids].each do |id| -%>
    <% experiment = Experiment.find(id) %>
    <% if experiment.can_view?-%>
        experiment_id = '<%= experiment.id -%>';
        experiment_title = '<%= escape_javascript(experiment.title) -%>';
        relationship_type = '<%= resource.is_a?(DataFile) ? escape_javascript(resource.relationship_type(experiment).try(:title) || "None") : 'None' -%>';
        addExperiment(experiment_title,experiment_id,relationship_type);
    <% end -%>
  <% end -%>
<% end -%>



  updateExperiments();

  check_show_add_experiment();
</script>

app/views/experiments/_associate_experiments.html.erb
<%
   resource_text ||= text_for_resource(resource)
   all_experiments=authorised_experiments.sort_by &:title
   all_experiments = authorised_experiments.select do |experiment|
     experiment.is_modelling?
   end if resource.is_a? Model

   project_experiments=authorised_experiments(current_user.person.projects).sort_by &:title
   project_experiments=project_experiments.select{|a| a.is_modelling?} if resource.is_a?(Model)
   select_truncate_length=120
   associated_experiments = resource.is_a?(Publication) ? resource.related_experiments : resource.experiments
%>

<div class="fold">

  <div class="foldTitle">
    <%= help_icon("Here you can associate Experiments in SEEK to this #{resource_text}. You can only associate Experiments you are authorized to edit.") -%>
    Experiments
  </div>

  <div id="associate_experiment_fold_content" class="foldContent" style="display:<%= associated_experiments.blank? ? 'none' : 'block' -%>">
    <div class="yui-u first" style="width:66%; float:left">

      <p style="color: #666666;">
        The following Experiments are involved in this <%= resource_text -%>:
      </p>
      <div id="experiment_to_list" class="box_editing_inner" style="line-height: 1.5">
        <span class="none_text" id="experiment_files">Loading...</span>
      </div>
      <div class="association_step">
        <p style="color: #666666;">
          You may select an existing Experiment or <%= link_to h("create a new Experiment here"), new_experiment_path(:create_from_asset=>:true),:popup => true%>  for the <%= resource_text -%>.
        </p>
        <% if show_relationships -%>
            <%= select_tag :possible_experiments,
                           options_for_select([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}),
                           {:style=>"width:90%",:onchange=>remote_function(
                                   :url=>{:action=>"preview",:controller=>"experiments",:element=>"experiment_preview"},
                                   :with=>"'id='+this.value",
                                   :before=>"show_ajax_loader('experiment_preview')"
                           )+";check_show_add_experiment();selected_experiment();return(false);"
                           } -%>
            <%= select_tag :experiment_ids,'',{:multiple=>true,:style=>"display:none;"} -%>
            <br/>
            <div id="relationship" style="display:none;">
              <%= label_tag "Relationship between the data and the model" %><br/>
              <%= select_tag :experiment_relationship_type, options_for_select([["None",0]] + RelationshipType.all.collect{|r| [r.title,r.id]}) %>
            </div>
            <br/>
        <% else %>
            <%= select_tag :possible_experiments,
                           options_for_select([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}),
                           {:style=>"width:90%",:onchange=>remote_function(
                                   :url=>{:action=>"preview",:controller=>"experiments",:element=>"experiment_preview"},
                                   :with=>"'id='+this.value",
                                   :before=>"show_ajax_loader('experiment_preview')"
                           )+";check_show_add_experiment();return(false);"
                           } -%>
            <%= select_tag :experiment_ids,'',{:multiple=>true,:style=>"display:none;"} -%>
            <br/>
            <br/>
        <% end %>
      </div>

      <br/>
      <%= link_to_function (image("new") + " Associate with this #{resource_text}"), "addSelectedExperiment(); return(false);", :id=>"add_experiment_link", :class=>"block_link" %>

      <%= check_box_tag :include_other_project_experiments, nil, false, {:onchange=>"toggle_experiment_list();",:style=>"margin-top:0.5em;"} -%> Associate Experiments from other projects?
    </div>

    <%= render :partial => 'assets/preview_box', :locals => {:preview_name => 'experiment'}%>

  </div>
</div>


<script type="text/javascript">
    function selected_experiment(){
        i = $('possible_experiments').selectedIndex;
        id = $('possible_experiments').options[i].value;
        for (var j = 0; j < id_rel_array.length; j++) {
            if ((id == id_rel_array[j][0]) && (id_rel_array[j][1] == 'true'))  {
                Effect.Appear('relationship',{duration:0.2});
            }
            else if ((id == id_rel_array[j][0]) && (id_rel_array[j][1] == 'false'))  {
                $('experiment_relationship_type').selectedIndex = 0;
                Effect.Fade('relationship',{duration:0.2});
            }
        }
    }

    function toggle_experiment_list() {
        var checked = $('include_other_project_experiments').checked;
        var selection_box = $('possible_experiments');
        var option;

        selection_box.options.length = 0;

        if (checked) {
        <% ([["Select Experiment ...",0]]|all_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}).each do |df_details| -%>
            option = document.createElement("OPTION");
            option.text = '<%= escape_javascript(df_details[0]) -%>';
            option.value = '<%= df_details[1] -%>';
            try {
                selection_box.add(option); //for older IE version
            }
            catch (ex) {
                selection_box.add(option, null);
            }
        <% end -%>
        }
        else {
        <% ([["Select Experiment ...",0]]|project_experiments.collect{|s| [truncate(h(s.title),:length=>select_truncate_length),s.id]}).each do |df_details| -%>
            option = document.createElement("OPTION");
            option.text = '<%= escape_javascript(df_details[0]) -%>';
            option.value = '<%= df_details[1] -%>';
            try {
                selection_box.add(option); //for older IE version
            }
            catch (ex) {
                selection_box.add(option, null);
            }
        <% end -%>
        }
        selection_box.selectedIndex = 0;
        selection_box.onchange();
    }

    <% associated_experiment_ids = resource.is_a?(Publication) ? resource.related_experiments.collect(&:id) : resource.experiments.collect(&:id) %>
    <% associated_experiment_ids.each do |associated_experiment_id|%>
    <% experiment = Experiment.find(associated_experiment_id) %>
    <% if experiment.try :can_view? -%>
    experiment_id = '<%= experiment.id -%>';
    experiment_title = '<%= experiment.title -%>';
    relationship_type = '<%= resource.is_a?(DataFile) ? escape_javascript(resource.relationship_type(experiment).try(:title) || "None") : 'None'-%>';
    addExperiment(experiment_title,experiment_id,relationship_type);
    <% end %>
    <% end -%>

    <% all_experiments.each do |experiment|%>
    experiment_id = '<%= experiment.id -%>';
    experiment_relationship = '<%=(experiment.is_modelling?) -%>';
    id_rel_array.push([experiment_id, experiment_relationship])
    <% end -%>

    <% if params[:experiment_ids] %>
    <% params[:experiment_ids].each do |id| -%>
    <% experiment = Experiment.find(id) %>
    <% if experiment.can_view?-%>
    experiment_id = '<%= experiment.id -%>';
    experiment_title = '<%= escape_javascript(experiment.title) -%>';
    relationship_type = '<%= resource.is_a?(DataFile) ? escape_javascript(resource.relationship_type(experiment).try(:title) || "None") : 'None' -%>';
    addExperiment(experiment_title,experiment_id,relationship_type);
    <% end -%>
    <% end -%>
    <% end -%>



    updateExperiments();

    check_show_add_experiment();
</script>

app/views/experiments/_associate_resource_list_item.html.erb
<%
   @experiment_text=resource.is_modelling? ? "Analysis" : "Experiment"
%>

<%= list_item_title resource %>


  <%= list_item_attribute "ID", resource.id %>

  <%= list_item_attribute "#{@experiment_text} type", resource.experiment_type.title.capitalize, resource.experiment_type %>
  <% unless resource.is_modelling? -%>
      <%= list_item_attribute "Technology type", resource.technology_type.title.capitalize, resource.technology_type %>
  <% end -%>

  <%= list_item_optional_attribute "Investigation", resource.investigation.try(:title), resource.investigation %>

  <%= list_item_optional_attribute "Study", resource.study.try(:title), resource.study %>

  <%= list_item_authorized_list(resource.models, "Models", true, 50, true) if resource.is_modelling? %>




  <%= list_item_attribute "Owner", resource.owner.name, resource.owner %>

  <%= render :partial => 'projects/show_project_relationship', :locals => {:resource => resource, :list_item => true} %>

<% if Seek::Config.organisms_enabled %>
  <%= list_item_simple_list(resource.experiment_organisms, "Organism") { |ao| experiment_organism_list_item(ao)  } %>
<% end %>
  <%= list_item_authorized_list resource.protocols, "Protocols", true, 50, true %>

  <%= list_item_authorized_list resource.data_files, "Data files", true, 50, true %>